all:
  vars:
    ansible_user: ubuntu
  children:
    kubernetes:
      children:
        control_plane:
        workers:
    edge:
      hosts:
        control_edge1:
        worker_edge2:
        worker_edge3:
    cloud:
      hosts:
        worker_cloud01:
        worker_cloud02:
        worker_cloud03:
    control_plane:
      hosts:
        control_edge1:
          ansible_host: 0.0.0.0
    workers:
      hosts:
        worker_edge2:
          ansible_host: 0.0.0.0
        worker_edge3:
          ansible_host: 0.0.0.0
        worker_cloud01:
          ansible_host: 0.0.0.0
        worker_cloud02:
          ansible_host: 0.0.0.0
        worker_cloud03:
          ansible_host: 0.0.0.0
    localhost:
      hosts:
        localhost_connection:
          ansible_connection: local
