---
- name: Reset kubeadm before running init
  hosts: kubernetes
  gather_facts: false
  become: true
  tasks:
    - name: Reset kubeadm
      ansible.builtin.shell: kubeadm reset -f
    - name: Remove $HOME/.kube/
      ansible.builtin.shell: rm -rf $HOME/.kube/
    - name: Remove CNI
      ansible.builtin.shell: rm -f /etc/cni/net.d/*
    - name: Reboot
      ansible.builtin.reboot:

- name: Setup K8S cluster
  hosts: control_plane
  become: true
  gather_facts: false
  tasks:
    - name: Initialize cluster with kubeadm
      ansible.builtin.shell: kubeadm init --pod-network-cidr=10.244.0.0/16

    - name: Interact with cluster
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        cp /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Let workers join cluster of master node
  hosts: workers
  gather_facts: false
  become: true
  tasks:
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['control_edge1'].join_command }}"
      args:
        chdir: $HOME

- name: Install/setup Flannel and set node labels
  hosts: control_plane
  gather_facts: false
  become: true
  tasks:
    - name: Install flannel
      ansible.builtin.shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

    - name: Set node labels
      ansible.builtin.shell: "kubectl label nodes {{ item.node }} {{ item.keyval }} --overwrite"
      loop:
        - { node: 'control_edge1', keyval: 'platform=edge' }
        - { node: 'worker_edge2', keyval: 'platform=edge' }
        - { node: 'worker_edge3', keyval: 'platform=edge' }
        - { node: 'worker_cloud01', keyval: 'platform=cloud' }
        - { node: 'worker_cloud02', keyval: 'platform=cloud' }
        - { node: 'worker_cloud03', keyval: 'platform=cloud' }
